//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinemas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class democinemaEntities : DbContext
    {

        private static democinemaEntities _context;
        public democinemaEntities()
            : base("name=democinemaEntities")
        {
        }

        public static democinemaEntities GetContext()
        {
            if (_context == null)
                _context = new democinemaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cinema> cinemas { get; set; }
        public virtual DbSet<film> films { get; set; }
        public virtual DbSet<seance> seances { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
