//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogame
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.game = new HashSet<game>();
        }
    
        public int id_clients { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual ICollection<game> game { get; set; }
    }
}
