//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demogame
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int id_game { get; set; }
        public string name_game { get; set; }
        public Nullable<System.DateTime> relise { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_gente { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual genre genre { get; set; }
    }
}
