//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demolast
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demofitnessEntities : DbContext
    {
        private static demofitnessEntities _context;
        public demofitnessEntities()
            : base("name=demofitnessEntities")
        {
        }

        public static demofitnessEntities GetContext()
        {
            if (_context == null)
                _context = new demofitnessEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fitness_clubs> fitness_clubs { get; set; }
        public virtual DbSet<lessons> lessons { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<types_sport> types_sport { get; set; }
    }
}
