//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class demoEntities : DbContext
    {
        private static demoEntities _context;

        public demoEntities()
            : base("name=demoEntities")
        {
        }

        public static demoEntities GetContext()
        {
            if (_context == null)
                _context = new demoEntities();
            return _context;
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<fintess_clubs> fintess_clubs { get; set; }
        public virtual DbSet<lessons> lessons { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<types_sport> types_sport { get; set; }
    }
}
