//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demofootball
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demofootballEntities : DbContext
    {
        private static demofootballEntities _contex; 

        public demofootballEntities()
            : base("name=demofootballEntities")
        {
        }

        public static demofootballEntities GetContext()
        {
            if (_contex == null)
                _contex = new demofootballEntities();
            return _contex;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<footballmatches> footballmatches { get; set; }
        public DbSet<footballplayers> footballplayers { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<teams> teams { get; set; }
    }
}
