//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demofootball
{
    using System;
    using System.Collections.Generic;
    
    public partial class footballplayers
    {
        public footballplayers()
        {
            this.footballmatches = new HashSet<footballmatches>();
        }
    
        public int id_footballplayer { get; set; }
        public string name_team { get; set; }
        public string FIO { get; set; }
        public Nullable<int> salary { get; set; }
    
        public virtual ICollection<footballmatches> footballmatches { get; set; }
    }
}
