//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demofootball
{
    using System;
    using System.Collections.Generic;
    
    public partial class footballmatches
    {
        public int id_footballmatches { get; set; }
        public string date_footballmatch { get; set; }
        public string name_comand { get; set; }
        public string name_comand2 { get; set; }
        public string point { get; set; }
        public string place_footballmatch { get; set; }
        public Nullable<int> id_team { get; set; }
        public Nullable<int> id_footballplayer { get; set; }
    
        public virtual footballplayers footballplayers { get; set; }
        public virtual teams teams { get; set; }
    }
}
